import frappe
from frappe import _
from frappe.core.doctype.file.exceptions import FileTypeNotAllowed
from frappe.core.doctype.file.file import File

# Extensions that must never be accepted through an HTTP upload, regardless of
# the admin "Allowed File Extensions" setting: server-interpretable code and
# browser-renderable active content (stored-XSS / web-shell vectors).
#
# Why this class exists: Frappe's built-in File.validate_file_extension() keys
# off the *guessed mimetype* and bails out early when the mimetype is unknown
# (`if not self.file_type ...: return`). mimetypes.guess_type("blan.php") is
# None, so `.php`/`.phtml` skip the allowlist entirely even when one is set.
# We enforce by the real filename extension instead, before the file is written
# to disk (validate_file_extension runs in before_insert, ahead of save_file).
BLOCKED_UPLOAD_EXTENSIONS = frozenset(
    {
        # PHP / server-interpretable
        "PHP", "PHP2", "PHP3", "PHP4", "PHP5", "PHP6", "PHP7", "PHTML",
        "PHT", "PHAR", "PHPS", "INC",
        # Browser-renderable active content
        "HTML", "HTM", "XHTML", "SHTML", "SVG", "SVGZ", "XML", "XSL", "XSLT",
        "MHT", "MHTML",
        # Scripts
        "JS", "MJS", "JSP", "JSPX", "ASP", "ASPX", "ASHX", "ASMX", "CER",
        "CGI", "PL", "PY", "RB", "SH", "BASH", "PS1", "VBS", "WSF",
        # Native executables / installers
        "EXE", "BAT", "CMD", "COM", "MSI", "SCR", "JAR", "DLL", "SO",
        "HTA", "SWF", "APP",
    }
)

# Server-config files that are dangerous by *name* rather than by extension:
# dropping one of these into a served directory can re-enable script execution
# or override auth. Matched against the whole normalised filename.
BLOCKED_FILE_NAMES = frozenset(
    {".HTACCESS", ".HTPASSWD", "WEB.CONFIG", ".USER.INI"}
)


def normalise_file_name(file_name: str | None) -> str:
    """Strip the padding used to smuggle an extension past a naive check.

    Trailing dots and whitespace are discarded by the filesystem/web server on
    save ("shell.php." is served as "shell.php"), and a NUL truncates the name
    in some C-backed paths -- so both must go *before* the name is parsed.
    """
    name = (file_name or "").split("\x00")[0]
    return name.strip().rstrip(". \t\r\n")


def extensions_of(file_name: str | None) -> list[str]:
    """Every dot-separated segment after the first, uppercased.

    All segments matter, not just the last: Apache mod_mime resolves
    "shell.php.jpg" as PHP because it walks the extensions right-to-left until
    it finds one it recognises, so an inner ".php" is still executable.
    """
    return [seg.strip().upper() for seg in normalise_file_name(file_name).split(".")[1:]]


def extension_of(file_name: str | None) -> str:
    """Uppercased final extension, without the dot ('' if none)."""
    exts = extensions_of(file_name)
    return exts[-1] if exts else ""


def check_upload_extension(file_name: str, allowed_extensions_setting: str | None) -> None:
    """Raise FileTypeNotAllowed if file_name is not permitted.

    Pure logic (no DB/request access) so it is unit-testable in isolation:
      1. dangerous server-config filenames are always blocked;
      2. dangerous extensions are always blocked, in *any* position;
      3. if an allowlist is configured, a final extension not on it is blocked
         (extensionless files are left alone to avoid breaking legitimate uploads).
    """
    def reject(label: str):
        frappe.throw(
            _("File type '{0}' is not allowed for upload.").format(label),
            exc=FileTypeNotAllowed,
        )

    if normalise_file_name(file_name).upper() in BLOCKED_FILE_NAMES:
        reject(normalise_file_name(file_name))

    exts = extensions_of(file_name)

    for ext in exts:
        if ext in BLOCKED_UPLOAD_EXTENSIONS:
            reject(ext)

    if allowed_extensions_setting:
        allowed_set = {
            e.strip().lstrip(".").upper()
            for e in allowed_extensions_setting.splitlines()
            if e.strip()
        }
        final_ext = exts[-1] if exts else ""
        if final_ext and final_ext not in allowed_set:
            reject(final_ext)


class CustomFile(File):
    def validate_file_extension(self):
        # Preserve Frappe's default mimetype-based allowlist behaviour.
        super().validate_file_extension()

        # Only guard real HTTP uploads, not files generated by code/integrations.
        if not frappe.request or not self.file_name:
            return

        check_upload_extension(
            self.file_name, frappe.get_system_settings("allowed_file_extensions")
        )
